name: build

on: 
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [K2P]
        toolchain: [mipsel-linux-uclibc, mipsel-linux-musl]
    steps:
      - uses: actions/checkout@main

      - uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ matrix.target }}-${{ matrix.toolchain }}
          append-timestamp: false

      - uses: actions/setup-go@main
        with:
          go-version: '1.20'
          check-latest: true
          cache: false

      - uses: actions/setup-node@main
        with:
          node-version: 18
          check-latest: true

      - name: Prepare
        run: |
          sudo apt update
          sudo apt install -y libtool-bin gperf python3-docutils autopoint gettext ccache

      - name: Build
        run: |
          make ${{ matrix.target }} TOOLCHAIN=${{ matrix.toolchain }}
          if [ "${{ matrix.target }}" = "K2P-NANO" ]; then
            image=$(ls trunk/images/*.trx)
            mv $image $(echo $image | sed 's/K2P/K2P-NANO/')
          fi

      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.toolchain }}
          path: trunk/images/*.trx

  publish:
    needs: [build]
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@main

      - uses: actions/download-artifact@main

      - name: Set Tag Name
        run: echo "TAG_ANME=$(date +%Y%m%d)" >> $GITHUB_ENV

      - uses: rickstaa/action-create-tag@main
        with:
          tag: ${{ env.TAG_ANME }}
          force_push_tag: true

      - uses: ncipollo/release-action@main
        with:
          commit: ${{ github.sha }}
          tag: ${{ env.TAG_ANME }}
          artifacts: "mipsel-linux-musl/*.trx"
          allowUpdates: true
